# Generated by Django 4.2.4 on 2023-08-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenName', models.CharField(max_length=100)),
                ('plantName', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('potSize', models.CharField(max_length=5)),
                ('height', models.IntegerField()),
            ],
        ),
    ]
