# Generated by Django 4.2.4 on 2023-08-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_meal_feeding_feed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeding',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='feeding',
            name='feed',
            field=models.CharField(choices=[('W', 'Water'), ('F', 'Liquid Fertiliser'), ('T', 'Plant Tonics')], default='W', max_length=1, verbose_name='feed type'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='potSize',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('X', 'Extra Large')], default='S', max_length=1, verbose_name='Pot size'),
        ),
    ]
