# Generated by Django 4.2.4 on 2023-08-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_enrichment_plant_enrichments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrichment',
            new_name='Extra',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='enrichments',
            new_name='extras',
        ),
    ]
