# Generated by Django 4.2.4 on 2023-08-18 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_rename_enrichment_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='givenName',
            field=models.CharField(max_length=100, verbose_name='Plant Name'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='height',
            field=models.IntegerField(verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plantName',
            field=models.CharField(max_length=100, verbose_name='Plant Type'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='potSize',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('X', 'Extra Large')], default='S', max_length=1, verbose_name='Pot Size'),
        ),
    ]
